### ISSUE TITLE
Authentication System

### ISSUE THREAD

**Issue by etsuo** [sakuraapi/api#18]

**Comment by gowthamrodda** [comment]
Its feels good to have a chance to participate in this opinionated SakuraApi development. Authentication plays a vital role in building a high security system of web 3.0. Hackers or intruders may find fun in braking a secured system with some hacking practices, however, there is much more fun in building an unhackable system. As the focus is more on developing more secured api's and having got typescript in plate, following    are few thoughts.
1. As API's are directly consumed by application clients, we can check weather client requests are authorized or not[a request is authorized when it agrees to our rules]. Unauthorized or invalid or non standard requests are blocked by server as a general practice.
2.  for SPA, or multipage app sends a request: , when user from client app provides valid username and password, general practice of setting common access token with expiry time is expected. However, we can limit users to access special api's by setting a special token respectively. which means along with common access token he has to provide special token for  special apis. This securely stops unauthorized users from accessing special apis. A special Api could be a core service/crucial implementation of data service. 
3. May be helmet js or Passport js are useful. or a custom implementation.
4. How about the idea of Two factor authentication- one using username/password, second - a one time token[valid for a particular period] generator.
5. Securing api's means securing models. The Base model from which all custom models are extended need to be a connected/persistant model [ connected to a data source ] that holds data instance from a collection or table.

these are my initial thoughts, and i am ready to work on different practices to implement a secure api.

**Comment by etsuo** [comment]
Hi @gowthamrodda and thanks for joining the project!

I think you're right in calling attention to needing to develop a strong security system around SakuraApi.

# Authentication vs Authorization
There are two separate, but related, concerns that we need to focus on: _authentication_ and _authorization_. **Authentication** is concerned with establishing that someone is who they claim to be. **Authorization** is concerned with establishing that someone has the right to perform some action. This ticket is primarily tracking the issue of authentication. Issue #7 is primarily concerned with tracking the issue of authorization. #7 would be what's responsible for the "special API" restrictions that @gowthamrodda mentions above in (2). 

# Rest API Scenario vs Server Side Rendered Scenario
In regards to authentication, there are two primary use-cases that I can think of, and how they're handled is slightly different. The first is the SPA (Single Page Application) / REST API use-case. This is where the client is responsible for its own UI rendering and maintaining its own state. Examples for the scenario include iOS / Android native clients, Ionic / Cordova type hybrid clients, Angular type clients, etc. The second use case is the the server side rendered scenario. This is where the server is responsible for generating pages and sending them to the browser. 

Let's call these two use cases the **REST API** scenario and the **server side rendered** scenario. I would argue that SakuraAPI is not designed to address the server side rendered scenario. It's designed to present a pure REST API void of any specific UI concerns. If that's the case, then we can discard the second scenario and focus on concerns related to authentication for REST APIs.

There are multiple ways one might get authenticated against a rest API. For our purposes, there are two primary use-cases: **native authentication** (username / password), and **oAuth 2 authentication**. I'm calling native authentication "native" because it doesn't rely on a third party broker. Other future use cases might involve including SAML support.

With any of these scenarios, at some point, once a user is authenticated, we need to return a secure token that represents that user's status as having been authenticated. I propose we use the Javascript Web Tokens standard (https://jwt.io/).

# Native and oAuth Scenarios
## Native Authentication
With the native authentication approach, things are pretty straight forward. A client gathers a user's username and password. It then send that to SakuraApi over HTTPS and SakuraApi does a lookup in a DB to make sure those credentials match. If they do, then a JWT token is created and handed back to the client. From that point forward, the client is responsible to inject the token into the HTTP header for each request going back to the server.

## oAuth Authentication
With oAuth, it gets a little bit more complicated. The client needs to (1) send the user to the oAuth provider (Facebook for example), there (2) the user is challenged for his credentials on that system, then (3) assuming that user is successfully authenticated on that provider, the provider sends back a short-lived token to the client, which then (4) must pass that token to the SakuraApi server so that (5) the SakuraApi server can request the user's profile directly from the oAuth 2 provider to ensure that (a) the short-lived token is valid and (b) that the email address for the user being authenticated is directly retrieved from the oAuth 2 provider (you can never trust anything the client gives you). This then leads to a possible (6) the server gets a long lived oAuth token and renewal token from the provider in case we want to automatically renew the token (this will be more important if we're also using this token to gain access to third-party apis on the provider on behalf of the user... for example posting to Facebook on behalf of the user). Then, (7), the server must generate a valid JWT token that is then passed back to the client.

With either scenario, the user is challenged for credentials to "prove" that they are who they claim to be and eventually, if those claims are validated, then a SakuraApi JWT authentication token is generated and sent to the client.

I like your suggestion that we support two-factor authentication out of the box. With native authentication, this is our responsibility. With oAuth, that's the responsibility of the provider (Facebook, Google, Github, etc.). 

**Some issues come to mind**:
* We're assuming the integrator of SakuraApi's authentication needs are as simple as a username/password. What if they also need to provide an account name or other form of domain identifier? 
* What if the SakuraApi integrator doesn't want to use email addresses, but instead they want to use usernames?
* What if the SakuraApi integrator wants to use usernames and/or email addresses to identify the user? (Imagine a system that collects the user's email address, but also lets them establish a username for public posting so that they don't have to expose their private email address)
* Some oAuth providers don't provide an email address (Twitter for example)
* What if a the SakuraApi integrator wants to allow his/her users to have multiple email addresses (this is a common use-case)
* We need to be able to support single user accounts with multiple authentication methods. For example, if a user starts with Facebook using johnny@sakuraapi.com, then authenticates with johnny@sakuraapi.com through Google's oAuth (assuming the SakuraApi integrator has allowed for both), then SakuraApi should recognize both as the same user based on the email address. That same user should be able to perform a password reset to then also gain access to native login with johnny@sakuraapi.com + password.

**Some other issues also come to mind**:
* Whatever the REST endpoints are that we implement, these should be customizable by the integrator.
* We should make it easy for the integrator to exclude the built-in authentication system so that they can provide their own totally custom authentication scheme.
* We should make it easy for the integrator to extend the built-in authentication system so that they can augment it with their own custom modules -- for example, they decide they need to support LDAP or SAML, etc, but they also want native authentication and oAuth2 support.
* If we allow a user to completely bypass the built in authentication system in favor of their own, we need to make sure we provide a clear internal API for that integrator to follow so that it'll work with the authorization system (ticket #7).
* Though we are not supporting the "server side rendered" use-case mentioned above, we will need the server to render certain pages for password resets that are emailed to the user and for telling the user their registration is complete after they click on the link emailed to them to verify they actually have the email address they provided.

# Misc. 
@gowthamrodda I like your idea of using helmetjs. I added a link to it on our wiki: https://github.com/sakuraapi/api/wiki/Integration-Candidates

In regards to Passport. I tried using it with Loopback on a project I'm currently working on and I found that it's really optimized for the server-side rendered scenario. With a pure REST API, the client application must initiate the oAuth2 challenge and then pass the token back to the API so that the server can validate that the token is both valid and resolves to the expected user. As far as I could tell, passport was not helpful with this scenario. Let me know if I'm wrong about that.

@gowthamrodda, you mention that a secure API means securing the models. I agree, but this is more of an authorization concern, so that'd be tracked by issue #7. I will say, however, that the way that the `@Model` decorator is being implemented right now, it will not rely on a base class. The reason for that is that I believe we should minimize contaminating the inheritance hierarchy in favor of leaving that wide open for the SakuraApi integrator to use or not use for whatever his/her needs are. Instead, `@model` is injecting default methods for things like `save` and `getById` if they're not specifically provided by the integrator (unless they're specifically blacklisted).  See issue #13.

# Two-Factor
I really like @gowthamrodda's desire to integrate two-factor support out of the box. We should keep that in mind as we're designing native authentication.

# Squirl (SQRL)
I'd like for us to explore supporting SQRL: https://www.grc.com/sqrl/sqrl.htm

# Blocking Dependencies
Before we can start to actually implement the authentication system, we need to finish implementing #13 and whatever related changes will be needed to support #13 in `@routable` / `@route`. That doesn't stop us from designing the authentication system now, however. ;)

@gowthamrodda thanks for getting the conversation started! I look forward to your continued contributions and feedback!

**Comment by gowthamrodda** [comment]
wow! @etsuo . Thats a detailed and outstanding explanation. Thanks a ton for the reply. SQRL looks promising(I havent gone through it yet, but I will). 
I would like to work off from feature/13 going forward and would update here.

**Comment by etsuo** [comment]
@gowthamrodda I'm hoping to have `feature/13` (#13) done in the next couple days then i'll merge it back into `develop`.

In the meantime if you want to experiment with the latest code, work with branch `feature/13` but just keep in mind that things are changing pretty quickly there. You'll need to Fork the repository.

Start by getting a good understanding of how the various decorators work: `@Model` (and the supporting decorators like `@Json`, `@Private`, etc,), `@Routable` and `@Route`, then join the Google group and start a thread to discuss what you want to work on: https://groups.google.com/forum/#!forum/sakuraapi -- once we coordinate there, we'll update the appropriate tickets here or create new ones to track the work.

If you want to work on this ticket (Authentication), it will likely get broken up into a bunch of smaller tickets first. There's a lot of work to do here! :) Also, you may want to coordinate with @MurthiiRandD, @RajuKaturi and @hari4olive - they have each expressed interest in contributing to the project, so you might be able to support each other as you learn how the foundation of the framework works. You'll want to make sure you have a good grasp of ES6 features like `Reflect`, `Proxy` and `Symbols`. Also, get familiar with https://www.npmjs.com/package/reflect-metadata. We're using `reflect-metadata` which is a proposal for ES7. Thx.

**Comment by etsuo** [comment]
Authentication is being implemented as separate middleware:
* https://github.com/sakuraapi/auth-native-authority

Future authentication middleware will include:
* auth-facebook-authority (issuer)
* auth-google-authority (issuer)
* auth-audience

This ticket is being closed and specific issues can be taken up in those projects as the need arises.
