### ISSUE TITLE
Bootstrap a @Routable class

### ISSUE THREAD

**Issue by etsuo** [sakuraapi/api#3]
Right now, you can't do this:
```
// ...

@Routable()
class SomeClass {
     constructor() {
          SakuraApi.instance.route(this);
     }
}
```

The reason why is the `sakuraApiClassRoutes` array hasn't been added to the object yet. See:  [routable.ts:Routable(...)](https://github.com/sakuraapi/api/blob/8b7458a7fa2043009b75ce5cfb1746283030da9c/core/routable.ts#L22).

Perhaps this could be refactored so the above scenario can become the pattern for bootstrapping a routable class.

Alternatively, a decorator could do the job:
```
// ...

@Routable()
@AddToRouter
class SomeClass {
     constructor() {
          SakuraApi.instance.route(this);
     }
}
```

Another possibility is maybe SakuraApi.instance.route(...) can be called from within Routable(...)??

**Comment by etsuo** [comment]
See 	95f99ed for implementation... basically, in a @Routable class will instantiate itself when the Decorator gets called during the class's declaration; when it's instantiated, part @Routable automatically adds it to the SakuraApi.instance.route(...) method. Thus, in virtue of declaring a class with the @Routable decorator, its @Route methods get added to the Express router.

**Comment by etsuo** [comment]
Done.

**Comment by Routable** [comment]
Check your at mentions.


Sent from my Bell Samsung device over Canada's largest network.


-------- Original message --------

**Comment by etsuo** [comment]
Sorry @Routable - turns out your user name is the same as one of my decorators... I'll do my best to remember to use `@Routable`
